name: mltools
dependencies:
  - python==3.6.0
  - jupyter
  - scipy
  - pandas
  - matplotlib
  - seaborn
  - scikit-learn
  - statsmodels
  - click
  - pip:
    - mlflow
    - xgboost
    - pygam
    - hyperopt
    - hpsklearn
